- hosts: all
  become: true

  tasks:
  - name: Install packages
    apt:
      state: present
      name: [
        'git',
        'tmux',
        'vim',
        'firefox',
        'thunderbird',
        'libreoffice',
        'pinta',
        'tuxpaint',
        'wine-stable',
        'winetricks'
      ]

  - name: Check if Google Chrome is installed
    shell: dpkg-query -W -f='${Status}' google-chrome-stable | grep '^install ok installed$'
    register: chrome_installed
    failed_when: no
    changed_when: no

  - name: Download Google Chrome
    get_url:
      url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dest: /tmp/google-chrome-stable_current_amd64.deb
    when: chrome_installed.rc != 0

  - name: Install Google Chrome
    shell: /usr/bin/dpkg -i /tmp/google-chrome-stable_current_amd64.deb || apt -y install -f
    when: chrome_installed.rc != 0
