- hosts: all
  become: true

  tasks:
  - name: Get package facts
    package_facts:
      manager: "auto"

  - name: Install packages
    apt:
      state: present
      name: [
        'git',
        'tmux',
        'vim',
        'firefox',
        'pinta',
        'tuxpaint',
      ]

  - name: Download Google Chrome
    get_url:
      url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dest: /tmp/google-chrome-stable_current_amd64.deb
    when: '"google-chrome-stable" not in ansible_facts.packages'

  - name: Install Google Chrome
    shell: /usr/bin/dpkg -i /tmp/google-chrome-stable_current_amd64.deb || /usr/bin/apt -y install -f
    when: '"google-chrome-stable" not in ansible_facts.packages'
